# Site settings
title: مدونتي الشخصية
tagline: مدونة شخصية لمشاركة أفكاري ومشاريعي وخبراتي
description: >-
  مدونة شخصية لمشاركة أفكاري ومشاريعي وخبراتي.
url: "https://ismaelfarah88.github.io"
baseurl: ""
lang: ar
timezone: Asia/Riyadh

# Author settings
author:
  name: Ismael farah
  email: asmael.net.sy@gmail.com
  twitter_username: ismael_farah1 
  github_username: ismaelfarah88
  avatar: /assets/img/avatar.jpg

# GitHub settings
github:
  username: ismaelfarah88

# Twitter settings
twitter:
  username: ismael_farah1
  card: summary

# Google Analytics
google_analytics:
  id: G-RLRKJFET27

# Theme settings
theme: jekyll-theme-chirpy
theme_mode: # [light|dark]
img_cdn: ""
avatar: https://avatars.githubusercontent.com/u/167617802?v=4

# boolean type, the global switch for TOC in posts.
toc: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-redirect-from

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Collections
collections:
  tabs:
    output: true
    sort_by: order

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
      toc: true
  - scope:
      path: ""
      type: "tabs"
    values:
      layout: page

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - .jekyll-cache
  - .sass-cache
  - LICENSE
  - README.md 