# Site settings
title: مدونتي الشخصية
tagline: مدونة شخصية لمشاركة أفكاري ومشاريعي وخبراتي
description: >-
  مدونة شخصية لمشاركة أفكاري ومشاريعي وخبراتي.
url: "https://ismaelfarah88.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
lang: ar
timezone: Asia/Riyadh

# Author settings
author:
  name: Ismael farah
  email: asmael.net.sy@gmail.com
  twitter_username: ismael_farah1 
  github_username: ismaelfarah88
  linkedin:
    username: username
    url: https://www.linkedin.com/in/username
  avatar: /assets/img/avatar.jpg

# GitHub settings
github:
  username: ismaelfarah88

# Twitter settings
twitter:
  username:  ismael_farah1
  card: summary

# Google Analytics
google_analytics:
  id: G-RLRKJFET27 # Google Analytics ID

# Theme settings
theme: jekyll-theme-chirpy
theme_mode: # [light|dark]
img_cdn: ""
avatar: https://avatars.githubusercontent.com/u/167617802?v=4

# The following settings are NECESSARY for the Chirpy theme to run:
baseurl: ""

# ------------ The following options are optional ------------

# Only if your site type is GitHub Project sites and doesn't have a custom domain,
# change below value to '/projectname'.
baseurl: ""

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
# e.g. 'https://cdn.com'
img_cdn:

# the avatar on sidebar, support local or CORS resources
avatar: https://avatars.githubusercontent.com/u/167617802?v=4

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  active: # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # optional, default to 'pathname'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development|production]

pwa:
  enabled: true # the option for PWA feature

paginate: 10

# ------------ The following options are for advanced users ------------

# The Jekyll core's default sass directory is '_sass'
sass:
  sass_dir: _sass
  style: compressed # [compressed|expanded]

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Collections
collections:
  tabs:
    output: true
    sort_by: order

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
      toc: true
      # for post
      math: false
      mermaid: false
      pin: false
  - scope:
      path: ""
      type: "tabs"
    values:
      layout: page
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-redirect-from

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - .jekyll-cache
  - .sass-cache
  - LICENSE
  - README.md 